spring.application.name=chat

spring.datasource.url=jdbc:postgresql://localhost:5432/ChatApp
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Security Config:
security.jwt.issuer=https://your-app.example
security.jwt.access-ttl=15m        # access token lifetime
security.jwt.refresh-ttl=2h        # absolute session window
security.jwt.private-key-path=file:keys/jwt-private.pem
security.jwt.public-key-path=file:keys/jwt-public.pem